stages:
  - test
  - deploy

test:
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python3-test-app
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 main.py

staging:
  stage: deploy
  script:
  - apt-get update -qy
  only:
  - master

production:
  stage: deploy
  script:
  - apt-get update -qy
  only:
  - tags