stages:
  - test
  - deploy

test:
  stage: test
  script:
  - pip install -r requirements.txt

staging:
  stage: deploy
  script:
  - pip install .
  only:
  - master

production:
  stage: deploy
  script:
  - python main.py
  only:
  - tags
